title: Rayvant Sahni
description: From the known towards the unknown
social_link: 'https://www.linkedin.com/in/rayvant-sahni/'
social_username: rayvant-sahni
github_repo: 'https://github.com/rayvantsahni'
github_username: rayvantsahni
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /ray
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
